name: Build Python Application with Alpine and PyInstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Alpine base image
        run: docker pull alpine:latest

      - name: Build Python application with PyInstaller
        run: |
          docker run --rm -v ${GITHUB_WORKSPACE}:/app alpine:latest \
            apk add python3 py3-pip zip
            pip3 install pyinstaller
            pip3 install -r requirements.txt
            pyinstaller --onefile --name QPDBot main.py
            mkdir dist/libs
            for lib in $(ldd dist/QPDBot | grep "=>" | awk '{print$3}'); do cp $lib dist/libs/; done
            zip -r dist.zip dist/
            ls

      

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist_zip
          path: dist.zip